language: node_js
node_js:
  - "0.10"

# http://rkh.github.io/travis-encrypt/public/index.html
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html

notifications:
  email:
    recipients:
      secure: Cc8afTsDQuKZBOP++FDqKFrD51saQnshUPBreTk+MCBQenksf7zq9w2Pt47EWqKKYB7HSKAwyb3EraUfv5UqoEFOm3bqmHSICUY3XOntRx+zBby/mlkvc6Qs67270hk7GqUWlSwX013sHSyqxZADRipAYf/GMfEYsbQ56vEyg8Y=
    on_success: always # change
    on_failure: always

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  #- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox

#after_script:
  #- ./node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --browsers=Firefox
  #- node node_modules/lcov-filter/index.js ./build/reports/coverage/report-lcov/lcov.info config | node node_modules/coveralls/bin/coveralls.js
  ##- ./node_modules/karma/bin/karma start
  ##- istanbul cover ./node_modules/mocha/bin/_mocha server/api/**/*.spec.js
  ##- cat ./coverage/lcov.info ./coverage/karma/**/*.info > lcov.info 
  ##- node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
